### ISSUE TITLE
Training Mode - Tie Explosions appear with a huge Position offset

### ISSUE THREAD

**Issue by rcpauor32** [Project-3-UPC-DDV-BCN/Project3#101]
* Description:
Tie Fighter explosions appears either with a high position offset (not on the Tie but far away) or on the Tie's original position.
* Severity:
C: Gameplay/art issues but don't prevent you from playing

* Steps to reproduce:
Enter Training mode, kill one tie fighter.

**Comment by ArmisJoe** [comment]
On the training scene there are

**Comment by rcpauor32** [comment]
I have already shown it to Roger Tello. It is imposible to capture via a Screenshot due to the enourmous offset (cannot have both Tie and Explosion at the same time).
And yes, in the training scene there are explosions, you can see it by yourself.
