### ISSUE TITLE
B - Can't shoot if you don't follow the target (duplicate of #67)

### ISSUE THREAD

**Issue by viriato22** [Project-3-UPC-DDV-BCN/Project3#102]
* Description: Can't shoot if you don't trigger the scene
###### Short description of the error

* Severity: B
###### C: Gameplay/art issues but don't prevent you from playing

* Steps to reproduce: Don't follow the target and instead go in the oposite direction
###### Steps to reproduce the bug

* Screenshot:
###### Screenshot showcasing the error
![ingame](https://user-images.githubusercontent.com/17138387/39863795-f213e700-5447-11e8-9a4b-82205badeb51.png)

**Comment by GuillemD** [comment]
It is intended. The player should follow the mission. This problem will be solved when adding soft-boundaries to the scene, as it will punish you if you go away.

**Comment by GuillemD** [comment]
duplicate of #67
