### ISSUE TITLE
First tie doesn't detect you

### ISSUE THREAD

**Issue by Trodek** [Project-3-UPC-DDV-BCN/Project3#125]
* Description:
If the player surpass the tie, it doesn't detect him and make him lose the game

* Severity:
C: Gameplay/art issues but don't prevent you from playing

* Steps to reproduce:
At the start of the campaign, speed up and go in front of the enemy tie.

* Screenshot:

**Comment by GuillemD** [comment]
I think that it could be solved by speeding up the tie, so there is no way to surpass it, instead of making it detect and shoot you.
