### ISSUE TITLE
Non updated version in main menu

### ISSUE THREAD

**Issue by GuillemD** [Project-3-UPC-DDV-BCN/Project3#22]
Description: The version that appears in the menu is still Vertical Slice 4
Severity: C
Reproduction steps: Click on the executable, look bot left corner

![bug](https://user-images.githubusercontent.com/15702926/39861502-103e3796-5441-11e8-94d5-7cff1228e1c1.png)

**Comment by Guillemsc** [comment]
Duplicate from #51

**Comment by SimonStoyanov** [comment]
Duplicate from #96

**Comment by SimonStoyanov** [comment]
You can close this one, the version has been updated
