### ISSUE TITLE
Wrong Control Screen

### ISSUE THREAD

**Issue by GuillemArman** [Project-3-UPC-DDV-BCN/Project3#28]
Type C 
Wrong Controls in Controls Menu Sprite before entering the game or pressing Start
![bug2](https://user-images.githubusercontent.com/17140302/39861750-d7fdccd8-5441-11e8-926b-dcb1f3313bae.png)

**Comment by dafral** [comment]
Eirini is working on this. I can't assign her because she is not in the github project
