### ISSUE TITLE
Game Icon

### ISSUE THREAD

**Issue by Trodek** [Project-3-UPC-DDV-BCN/Project3#43]
* Description:
The game should have an application icon

* Severity:
C: Gameplay/art issues but don't prevent you from playing

* Steps to reproduce:
Open the game and look to the task bar

* Screenshot:
![image](https://user-images.githubusercontent.com/17142220/39862215-63ce1064-5443-11e8-8715-da4fd8ee0124.png)

![image](https://user-images.githubusercontent.com/17142220/39862229-6aea08bc-5443-11e8-80ec-630ebb254382.png)

**Comment by dafral** [comment]
We can do a new logo if it's needed
