### ISSUE TITLE
Audio not paused with pause screen

### ISSUE THREAD

**Issue by GuillemD** [Project-3-UPC-DDV-BCN/Project3#44]
* Description:
###### All audio continues after the game is paused

* Severity:
###### C: Gameplay/art issues but don't prevent you from playing

* Steps to reproduce:
###### Start campaign, pass controls screens, destroy 3 intro ships, pause.

* Screenshot:

**Comment by SimonStoyanov** [comment]
@rogerbusquets97 To pause the game i need an event for pausing and an event for resuming from wwise
https://www.audiokinetic.com/library/2017.1.6_6446/?source=WwiseProjectAdventure&id=pausing_game
https://www.audiokinetic.com/library/2017.1.6_6446/?source=WwiseProjectAdventure&id=resuming_game

**Comment by SimonStoyanov** [comment]
![image](https://user-images.githubusercontent.com/17119542/39967959-557d4d3e-56c5-11e8-8cc7-dbdf931c7b9d.png)

![image](https://user-images.githubusercontent.com/17119542/39967957-4b753cd4-56c5-11e8-871d-a980da918d7d.png)

**Comment by SimonStoyanov** [comment]
Issue solved
