### ISSUE TITLE
Build Version

### ISSUE THREAD

**Issue by Trodek** [Project-3-UPC-DDV-BCN/Project3#51]
* Description:
The build version must be the current one, not Vertical Slice 4

* Severity:
C: Gameplay/art issues but don't prevent you from playing

* Steps to reproduce:
At the main menu, look at the bottom left corner where the build version appears 

* Screenshot:
![image](https://user-images.githubusercontent.com/17142220/39862405-0202787e-5444-11e8-8b09-23f23bb76448.png)

**Comment by SimonStoyanov** [comment]
The version has been updated, this issue can be closed
