### ISSUE TITLE
Campaign should be a mission

### ISSUE THREAD

**Issue by Trodek** [Project-3-UPC-DDV-BCN/Project3#54]
* Description:
The Campaign Button should say mission instead

* Severity:
C: Gameplay/art issues but don't prevent you from playing

* Steps to reproduce:
Look at the main menu UI, it is the first option.

* Screenshot:
![image](https://user-images.githubusercontent.com/17142220/39862499-4f3452b6-5444-11e8-941b-5a0dce5dcf50.png)

**Comment by ArmisJoe** [comment]
Should be fixed @Trodek
