### ISSUE TITLE
3D audio positioning not working properly.

### ISSUE THREAD

**Issue by rogerbusquets97** [Project-3-UPC-DDV-BCN/Project3#59]
* Description:
3D audio positioning not working properly, sometimes some of the Tie Fighters (that are the ones that uses 3D positioning audio) do not reproduce the audio properly according their 3D position, it provoques silence sometimes. 

* Severity:
 C: Gameplay/art issues but don't prevent you from playing

* Steps to reproduce:
Whenever a sound object with 3D positioning sends his position to Wwise.

* Screenshot:
Select the image to see better the error. Says the following: 

_At: Wwise.cpp => SetPosition() => Line: 324. Vectors are not orthogonal!_

![image](https://user-images.githubusercontent.com/17140300/39862433-168908e4-5444-11e8-8335-f8ab3715ccaf.png)

**Comment by SimonStoyanov** [comment]
@rogerbusquets97 I need you to be more specific at the *Steps to reproduce*, I could not replicate the same output as you
