### ISSUE TITLE
Lasers' Volume too loud

### ISSUE THREAD

**Issue by rcpauor32** [Project-3-UPC-DDV-BCN/Project3#77]
* Description:
Slave 1 lasers' volume is too loud respect other sfx and music.

* Severity:
C: Gameplay/art issues but don't prevent you from playing

* Steps to reproduce:
 Play Campaign mode, start shooting.

**Comment by dafral** [comment]
I don't understand the issue. I need more information 😖

**Comment by rcpauor32** [comment]
I hear the Player's lasers so loud they are beyond anoying while I can't nearly hear the other FXs.
