### ISSUE TITLE
Second weapon doesn't charge (no feedback)

### ISSUE THREAD

**Issue by GuillemD** [Project-3-UPC-DDV-BCN/Project3#94]
* Description:
###### When click the shoot button with the second weapon equiped, there's no feedback for the charge state of the weapon.

* Severity:
###### C: Gameplay/art issues but don't prevent you from playing

* Steps to reproduce:
###### Start campaign, change weapon, press and maintain shoot button.

* Screenshot:
![bug6](https://user-images.githubusercontent.com/15702926/39863600-6da0d938-5447-11e8-9abc-3e110b68b49b.png)

**Comment by sergipa** [comment]
Fixed, with the new weapon system it works correctly

**Comment by GuillemD** [comment]
Checked
